_BASE_: "./utt.yaml"
MODEL:
  BACKBONE:
    FROZEN_STAGES: -1
    NORM: SyncBN
  FEATURE_DIM: 512
  OBJECT_SIZE: 1
  SOT:
    FEATURE_DIM: 512
    BOX_HEAD:
      INPUT_DIM: 512
      HIDDEN_DIM: 512
  TRACK_HEAD:
    OUTPUT_SCORE: False
    ITERATIONS: 6
    FEATURE_DIM: 512
    DIM_FEEDFORWARD: 1024
    DROPOUT: 0.1
    EXPAND_SCALE: 1.0

SOT:
  DATASET:
    ROOT: "./data"
    MAX_SAMPLE_INTERVAL: 200
    SEARCH:
      SIZE: 352
      FACTOR: 6.0
      CENTER_JITTER: 5.5
      SCALE_JITTER: 0.5
      FRAMES: 3

  DATALOADER:
    NUM_WORKERS: 4
    STACK_DIM: 0
    COLLATE_FN: 'trival'
    BATCH_SIZE: 64


SOLVER:
  MAX_ITER: 400000
  BASE_LR: 1e-5
  OPTIMIZER_NAME: "adamw"
  LR_SCHEDULER:
    NAME: "cosine"
    DECAY_STEP: 3000
    WARMUP_ITERS: 200
    WARMUP_LR: 1e-6
    LR_MIN: 1e-7
  CHECKPOINT_PERIOD: 10000


OUTPUT_DIR: "./outputs"
SYNC_BN: True

SEED: 0
